cd tools
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/PIZZ01.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/PIZZ01.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/PIZZ02.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/PIZZ02.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/PIZZ03.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/PIZZ03.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/PIZZ04.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/PIZZ04.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/PIZZ05.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/PIZZ05.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/PIZZ06.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/PIZZ06.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/PIZZ07.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/PIZZ07.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/PIZZ08.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/PIZZ08.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/PIZZ09.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/PIZZ09.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/PIZZ10.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/PIZZ10.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/PIZZ11.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/PIZZ11.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/PIZZ12.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/PIZZ12.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/PIZZ13.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/PIZZ13.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/PIZZ14.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/PIZZ14.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/PIZZ15.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/PIZZ15.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/PIZZ16.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/PIZZ16.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/PIZZ17.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/PIZZ17.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/PIZZ18.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/PIZZ18.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/PIZZ19.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/PIZZ19.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/PIZZ20.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/PIZZ20.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/PIZZ21.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/PIZZ21.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/PIZZ22.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/PIZZ22.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/PIZZ23.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/PIZZ23.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/PIZZ24.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/PIZZ24.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/PIZZ25.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/PIZZ25.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/PIZZ26.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/PIZZ26.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/PIZZ27.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/PIZZ27.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/PIZZ28.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/PIZZ28.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/PIZZ29.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/PIZZ29.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/PIZZ30.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/PIZZ30.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/PIZZ31.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/PIZZ31.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/PIZZ32.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/PIZZ32.wad.hm"
cd E:/GitHub/LexWadExtract/pk3/maps/
del /q "*.dm"
del /q "wait.txt"
exit