cd tools
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/GODW01.WAD.DM" "E:/GitHub/LexWadExtract/pk3/maps/GODW01.WAD.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/GODW02.WAD.DM" "E:/GitHub/LexWadExtract/pk3/maps/GODW02.WAD.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/GODW03.WAD.DM" "E:/GitHub/LexWadExtract/pk3/maps/GODW03.WAD.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/GODW04.WAD.DM" "E:/GitHub/LexWadExtract/pk3/maps/GODW04.WAD.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/GODW05.WAD.DM" "E:/GitHub/LexWadExtract/pk3/maps/GODW05.WAD.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/GODW06.WAD.DM" "E:/GitHub/LexWadExtract/pk3/maps/GODW06.WAD.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/GODW07.WAD.DM" "E:/GitHub/LexWadExtract/pk3/maps/GODW07.WAD.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/GODW08.WAD.DM" "E:/GitHub/LexWadExtract/pk3/maps/GODW08.WAD.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/GODW09.WAD.DM" "E:/GitHub/LexWadExtract/pk3/maps/GODW09.WAD.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/GODW10.WAD.DM" "E:/GitHub/LexWadExtract/pk3/maps/GODW10.WAD.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/GODW11.WAD.DM" "E:/GitHub/LexWadExtract/pk3/maps/GODW11.WAD.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/GODW12.WAD.DM" "E:/GitHub/LexWadExtract/pk3/maps/GODW12.WAD.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/GODW13.WAD.DM" "E:/GitHub/LexWadExtract/pk3/maps/GODW13.WAD.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/GODW14.WAD.DM" "E:/GitHub/LexWadExtract/pk3/maps/GODW14.WAD.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/GODW15.WAD.DM" "E:/GitHub/LexWadExtract/pk3/maps/GODW15.WAD.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/GODW16.WAD.DM" "E:/GitHub/LexWadExtract/pk3/maps/GODW16.WAD.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/GODW17.WAD.DM" "E:/GitHub/LexWadExtract/pk3/maps/GODW17.WAD.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/GODW18.WAD.DM" "E:/GitHub/LexWadExtract/pk3/maps/GODW18.WAD.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/GODW19.WAD.DM" "E:/GitHub/LexWadExtract/pk3/maps/GODW19.WAD.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/GODW20.WAD.DM" "E:/GitHub/LexWadExtract/pk3/maps/GODW20.WAD.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/GODW21.WAD.DM" "E:/GitHub/LexWadExtract/pk3/maps/GODW21.WAD.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/GODW22.WAD.DM" "E:/GitHub/LexWadExtract/pk3/maps/GODW22.WAD.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/GODW23.WAD.DM" "E:/GitHub/LexWadExtract/pk3/maps/GODW23.WAD.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/GODW24.WAD.DM" "E:/GitHub/LexWadExtract/pk3/maps/GODW24.WAD.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/GODW25.WAD.DM" "E:/GitHub/LexWadExtract/pk3/maps/GODW25.WAD.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/GODW26.WAD.DM" "E:/GitHub/LexWadExtract/pk3/maps/GODW26.WAD.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/GODW27.WAD.DM" "E:/GitHub/LexWadExtract/pk3/maps/GODW27.WAD.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/GODW28.WAD.DM" "E:/GitHub/LexWadExtract/pk3/maps/GODW28.WAD.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/GODW29.WAD.DM" "E:/GitHub/LexWadExtract/pk3/maps/GODW29.WAD.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/GODW30.WAD.DM" "E:/GitHub/LexWadExtract/pk3/maps/GODW30.WAD.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/GODW31.WAD.DM" "E:/GitHub/LexWadExtract/pk3/maps/GODW31.WAD.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/GODW32.WAD.DM" "E:/GitHub/LexWadExtract/pk3/maps/GODW32.WAD.hm"
cd E:/GitHub/LexWadExtract/pk3/maps/
del /q "*.dm"
del /q "wait.txt"
exit