cd tools
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/VALR01.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/VALR01.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/VALR02.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/VALR02.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/VALR03.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/VALR03.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/VALR04.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/VALR04.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/VALR05.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/VALR05.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/VALR06.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/VALR06.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/VALR07.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/VALR07.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/VALR08.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/VALR08.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/VALR09.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/VALR09.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/VALR10.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/VALR10.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/VALR11.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/VALR11.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/VALR12.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/VALR12.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/VALR13.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/VALR13.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/VALR14.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/VALR14.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/VALR15.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/VALR15.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/VALR16.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/VALR16.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/VALR17.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/VALR17.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/VALR18.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/VALR18.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/VALR19.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/VALR19.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/VALR20.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/VALR20.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/VALR21.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/VALR21.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/VALR22.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/VALR22.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/VALR23.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/VALR23.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/VALR24.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/VALR24.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/VALR25.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/VALR25.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/VALR26.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/VALR26.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/VALR27.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/VALR27.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/VALR28.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/VALR28.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/VALR29.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/VALR29.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/VALR30.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/VALR30.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/VALR31.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/VALR31.wad.hm"
E:/GitHub/LexWadExtract/tools/zwadconv.exe "E:/GitHub/LexWadExtract/pk3/maps/VALR32.wad.dm" "E:/GitHub/LexWadExtract/pk3/maps/VALR32.wad.hm"
cd E:/GitHub/LexWadExtract/pk3/maps/
del /q "*.dm"
del /q "wait.txt"
exit