D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CCST01.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CCST01.WAD.HM
ren "convlog.txt" "CCST01.WAD.DM_convlog.txt"
move "CCST01.WAD.DM_convlog.txt" "logs"
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CCST02.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CCST02.WAD.HM
ren "convlog.txt" "CCST02.WAD.DM_convlog.txt"
move "CCST02.WAD.DM_convlog.txt" "logs"
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CCST03.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CCST03.WAD.HM
ren "convlog.txt" "CCST03.WAD.DM_convlog.txt"
move "CCST03.WAD.DM_convlog.txt" "logs"
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CCST04.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CCST04.WAD.HM
ren "convlog.txt" "CCST04.WAD.DM_convlog.txt"
move "CCST04.WAD.DM_convlog.txt" "logs"
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CCST05.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CCST05.WAD.HM
ren "convlog.txt" "CCST05.WAD.DM_convlog.txt"
move "CCST05.WAD.DM_convlog.txt" "logs"
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CCST06.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CCST06.WAD.HM
ren "convlog.txt" "CCST06.WAD.DM_convlog.txt"
move "CCST06.WAD.DM_convlog.txt" "logs"
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CCST07.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CCST07.WAD.HM
ren "convlog.txt" "CCST07.WAD.DM_convlog.txt"
move "CCST07.WAD.DM_convlog.txt" "logs"
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CCST08.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CCST08.WAD.HM
ren "convlog.txt" "CCST08.WAD.DM_convlog.txt"
move "CCST08.WAD.DM_convlog.txt" "logs"
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CCST09.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CCST09.WAD.HM
ren "convlog.txt" "CCST09.WAD.DM_convlog.txt"
move "CCST09.WAD.DM_convlog.txt" "logs"
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CCST10.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CCST10.WAD.HM
ren "convlog.txt" "CCST10.WAD.DM_convlog.txt"
move "CCST10.WAD.DM_convlog.txt" "logs"
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CCST11.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CCST11.WAD.HM
ren "convlog.txt" "CCST11.WAD.DM_convlog.txt"
move "CCST11.WAD.DM_convlog.txt" "logs"
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CCST12.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CCST12.WAD.HM
ren "convlog.txt" "CCST12.WAD.DM_convlog.txt"
move "CCST12.WAD.DM_convlog.txt" "logs"
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CCST13.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CCST13.WAD.HM
ren "convlog.txt" "CCST13.WAD.DM_convlog.txt"
move "CCST13.WAD.DM_convlog.txt" "logs"
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CCST14.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CCST14.WAD.HM
ren "convlog.txt" "CCST14.WAD.DM_convlog.txt"
move "CCST14.WAD.DM_convlog.txt" "logs"
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CCST15.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CCST15.WAD.HM
ren "convlog.txt" "CCST15.WAD.DM_convlog.txt"
move "CCST15.WAD.DM_convlog.txt" "logs"
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CCST16.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CCST16.WAD.HM
ren "convlog.txt" "CCST16.WAD.DM_convlog.txt"
move "CCST16.WAD.DM_convlog.txt" "logs"
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CCST17.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CCST17.WAD.HM
ren "convlog.txt" "CCST17.WAD.DM_convlog.txt"
move "CCST17.WAD.DM_convlog.txt" "logs"
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CCST18.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CCST18.WAD.HM
ren "convlog.txt" "CCST18.WAD.DM_convlog.txt"
move "CCST18.WAD.DM_convlog.txt" "logs"
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CCST19.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CCST19.WAD.HM
ren "convlog.txt" "CCST19.WAD.DM_convlog.txt"
move "CCST19.WAD.DM_convlog.txt" "logs"
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CCST20.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CCST20.WAD.HM
ren "convlog.txt" "CCST20.WAD.DM_convlog.txt"
move "CCST20.WAD.DM_convlog.txt" "logs"
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CCST21.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CCST21.WAD.HM
ren "convlog.txt" "CCST21.WAD.DM_convlog.txt"
move "CCST21.WAD.DM_convlog.txt" "logs"
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CCST22.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CCST22.WAD.HM
ren "convlog.txt" "CCST22.WAD.DM_convlog.txt"
move "CCST22.WAD.DM_convlog.txt" "logs"
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CCST23.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CCST23.WAD.HM
ren "convlog.txt" "CCST23.WAD.DM_convlog.txt"
move "CCST23.WAD.DM_convlog.txt" "logs"
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CCST24.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CCST24.WAD.HM
ren "convlog.txt" "CCST24.WAD.DM_convlog.txt"
move "CCST24.WAD.DM_convlog.txt" "logs"
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CCST25.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CCST25.WAD.HM
ren "convlog.txt" "CCST25.WAD.DM_convlog.txt"
move "CCST25.WAD.DM_convlog.txt" "logs"
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CCST26.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CCST26.WAD.HM
ren "convlog.txt" "CCST26.WAD.DM_convlog.txt"
move "CCST26.WAD.DM_convlog.txt" "logs"
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CCST27.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CCST27.WAD.HM
ren "convlog.txt" "CCST27.WAD.DM_convlog.txt"
move "CCST27.WAD.DM_convlog.txt" "logs"
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CCST28.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CCST28.WAD.HM
ren "convlog.txt" "CCST28.WAD.DM_convlog.txt"
move "CCST28.WAD.DM_convlog.txt" "logs"
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CCST29.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CCST29.WAD.HM
ren "convlog.txt" "CCST29.WAD.DM_convlog.txt"
move "CCST29.WAD.DM_convlog.txt" "logs"
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CCST30.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CCST30.WAD.HM
ren "convlog.txt" "CCST30.WAD.DM_convlog.txt"
move "CCST30.WAD.DM_convlog.txt" "logs"
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CCST31.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CCST31.WAD.HM
ren "convlog.txt" "CCST31.WAD.DM_convlog.txt"
move "CCST31.WAD.DM_convlog.txt" "logs"
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CCST32.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CCST32.WAD.HM
ren "convlog.txt" "CCST32.WAD.DM_convlog.txt"
move "CCST32.WAD.DM_convlog.txt" "logs"
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CCST35.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CCST35.WAD.HM
ren "convlog.txt" "CCST35.WAD.DM_convlog.txt"
move "CCST35.WAD.DM_convlog.txt" "logs"
cd D:/GitHub/LexWadExtract/pk3/MAPS/
del "*.DM" /q
del "wait.txt"
exit