D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE01.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE01.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE02.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE02.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE03.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE03.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE04.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE04.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE05.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE05.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE06.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE06.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE07.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE07.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE08.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE08.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE09.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE09.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE10.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE10.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE11.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE11.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE12.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE12.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE13.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE13.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE14.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE14.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE15.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE15.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE16.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE16.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE17.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE17.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE18.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE18.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE19.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE19.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE20.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE20.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE21.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE21.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE22.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE22.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE23.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE23.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE24.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE24.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE25.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE25.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE26.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE26.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE27.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE27.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE28.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE28.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE29.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE29.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE30.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE30.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE31.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE31.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE32.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE32.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE33.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE33.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE34.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE34.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE35.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE35.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE36.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE36.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE37.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE37.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE38.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE38.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE39.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE39.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE40.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE40.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE41.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE41.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE42.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE42.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE43.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE43.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE44.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE44.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE45.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE45.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE46.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE46.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE47.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE47.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE48.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE48.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE49.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE49.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE50.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE50.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE51.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE51.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE52.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE52.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE53.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE53.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE54.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE54.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE55.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE55.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE56.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE56.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE57.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE57.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE58.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE58.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE59.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE59.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE60.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE60.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE61.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE61.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE62.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE62.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE63.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE63.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE64.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE64.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE65.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE65.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE66.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE66.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE67.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE67.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE68.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE68.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE69.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE69.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE70.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE70.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE71.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE71.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE72.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE72.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE73.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE73.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE74.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE74.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE75.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE75.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE76.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE76.WAD.HM
D:/GitHub/LexWadExtract/tools/extractor/tools/zwadconv D:/GitHub/LexWadExtract/pk3/MAPS/CORE77.WAD.DM D:/GitHub/LexWadExtract/pk3/MAPS/CORE77.WAD.HM
cd D:/GitHub/LexWadExtract/pk3/MAPS/
del "*.DM" /q
del "wait.txt"
exit